#!/usr/bin/env bash
# Displays numbers 1-20 with cultural bad luck messages using case
counter=1
while [ $counter -le 20 ]
do
    echo "$counter"
    case $counter in
        4) echo "bad luck from China" ;;
        9) echo "bad luck from Japan" ;;
        17) echo "bad luck from Italy" ;;
    esac
    ((counter++))
done
